### ISSUE TITLE
Fix Video Playback

### ISSUE THREAD

**Issue by bjohnson5** [watermarkchurch/Community-App-Android#4]
Currently no videos will play. This is because the links in the content are youtube links and not links to video files. Need to find a solution that will allow us to play youtube links.

**Comment by bjohnson5** [comment]
@ddukesterman @frizman21 The community app content contains a lot of youtube URLs for video. The default VideoView class in android does not appear to work with them. Do we have any other examples of an app handling URLs that are not specific video files. The RTRQ app content used URLs that pointed to a specific file name.

**Comment by frizman21** [comment]
Not sure that I understand yet. I assume there's a way to play a YouTube view in an Android app. Are not providing the right information about the YouTube video?

**Comment by bjohnson5** [comment]
Yeah I was assuming they would play the same way that the RTRQ videos played, but the VideoView does not like something about the YouTube URL. So I was just checking if you guys had used any kind of YouTube API or had a standard way of playing the videos. I believe that the VideoView is looking for a specific file extension like .mp4 and the YouTube links are simply URLs.

**Comment by frizman21** [comment]
We have an iframe that available, but I think we'd rather invert the question - what do we need to do to play YouTube videos on Android? For example, I know that sometimes it doesn't like the youtube shortened URLs - let us know and we'll resolve the actual URL if necessary. Let me know what you need!
